name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: ✨ New Features
    labels: [feature]
  - title: 🐛 Bug Fixes
    labels: [bug]
  - title: 🧰 Maintenance
    labels: [chore]
  - title: 📜 Documentation
    labels: [docs]
  - title: ⬆️ Dependencies
    labels: [dependencies]

exclude-labels:
  - skip-changelog

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

template: |
  ## Release: $RESOLVED_VERSION

  ### What's Changed
  $CHANGES

  ### Contributors
  $CONTRIBUTORS