# ============================================
# Workflow: docker-release-from-tag.yml
# Purpose: Build Docker image and JAR from a Git tag using version in build.gradle
# Publishes Docker image: reddy1990/demo-actions:<version>-<shortSHA>-build-<run_number>
# Uploads JAR as GitHub release asset
# Also generates release notes including merged PRs
# ============================================

name: Docker Release from Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Extract version and metadata from build.gradle
        id: meta
        run: |
          VERSION=$(grep '^version' build.gradle | sed "s/version\s*=\s*['\"]//;s/['\"]//g")
          SHORT_SHA=$(git rev-parse --short HEAD)
          BUILD_NUM=${{ github.run_number }}

          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "BUILD_NUM=$BUILD_NUM" >> $GITHUB_OUTPUT

      - name: Build JAR
        run: ./gradlew clean bootJar

      - name: List files in build/libs
        run: ls -l build/libs

      - name: Build Docker image
        run: |
          docker build -t demo-actions:${{ steps.meta.outputs.VERSION }}-${{ steps.meta.outputs.SHORT_SHA }}-build-${{ steps.meta.outputs.BUILD_NUM }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag demo-actions:${{ steps.meta.outputs.VERSION }}-${{ steps.meta.outputs.SHORT_SHA }}-build-${{ steps.meta.outputs.BUILD_NUM }} \
            reddy1990/demo-actions:${{ steps.meta.outputs.VERSION }}-${{ steps.meta.outputs.SHORT_SHA }}-build-${{ steps.meta.outputs.BUILD_NUM }}
          docker push reddy1990/demo-actions:${{ steps.meta.outputs.VERSION }}-${{ steps.meta.outputs.SHORT_SHA }}-build-${{ steps.meta.outputs.BUILD_NUM }}

      - name: Get previous tag
        id: prevtag
        run: |
          TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "PREV_TAG=$TAG" >> $GITHUB_OUTPUT

      - name: 'Build Changelog'
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
            token: '${{ github.token }}'

      - name: Create GitHub Release with notes and JAR
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.meta.outputs.VERSION }}
          name: v${{ steps.meta.outputs.VERSION }}
          body: ${{steps.build_changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
