name: Release on Tag

on:
  push:
    tags:
      - 'v8*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java (for Gradle projects)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions to Gradle
        run: chmod +x ./gradlew

      - name: Build the JAR
        run: ./gradlew clean build

      - name: List files in build/libs
        run: ls -l build/libs

      - name: Parse version from build.gradle
        id: version
        run: |
          VERSION=$(grep '^version' build.gradle | sed "s/version\s*=\s*['\"]//;s/['\"]//g")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}